server:
  port: 8081

spring:
  application:
    name: data-service

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        tags:
          - version=1.0-SNAPSHOT
        #register-health-check: false
        health-check-interval: 5s
        health-check-path: /actuator/health
        # Use below config instead for docker and replace localhost with actual IP addr:
        #health-check-url: http://localhost:8081/actuator/health

feign:
  circuitbreaker:
    enabled: true

logging:
  level:
    root: info
    com.nomura.sample: debug

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics

sample:
  feign.client:
    name: data-service

  default-cost-millis: 500
  data:
    - name: Fujun Yang
      email: fujun.yang@nomura.com
      department: WDOT Market Data Services
      location: Shanghai (Central Plaza 31FL)
      webex: https://nomura.webex.com/meet/fujun.yang | 2610 697 0331

    - name: Yifan Zhuang
      email: yifan.zhuang@nomura.com
      department: WDOT Market Data Services
      location: Shanghai (Central Plaza 31FL)
