server:
  port: 8081

spring:
  application:
    name: data-service

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null

  cloud:
    kubernetes:
      config:
        name: sample-data-service-app-config     # Does NOT work here, but works well with parameter or env variables
      reload:
        enabled: true
        #mode: event                  # default as Event, alternative Polling using period of interval (default 15s)
        #strategy: restart_context    # default as Refresh only applied to @ConfigurationProperties and @RefreshScope

feign:
  circuitbreaker:
    enabled: true

logging:
  level:
    root: info
    com.nomura.sample: debug

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics

sample:
  feign.client:
    name: sample-client
    url: http://sample-data-service:8081/

  default-cost-millis: 500
