server:
  port: 8081

spring:
  application:
    name: data-service

logging:
  level:
    root: info
    com.nomura.sample: debug

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/