apiVersion: v1
kind: Service
metadata:
  labels:
    app: sample-gateway-service
  name: sample-gateway-service
spec:
  ports:
  - name: sample-gateway-svc-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: sample-gateway-service
  type: ClusterIP
