apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sample-role-reader
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["configmaps", "pods", "services", "secrets"]
    verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sample-role-reader-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sample-role-reader
subjects:
  - kind: ServiceAccount
    name: sample-service-account

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: sample-service-account
  namespace: default