apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: data-service
  name: data-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: data-service
  template:
    metadata:
      labels:
        app: data-service
    spec:
      containers:
      - image: data-service:1.0-SNAPSHOT
        name: data-service
        resources: {}
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8081
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8081
        lifecycle:  # Enable graceful shutdown
          preStop:
            exec:
              command: ["sh", "-c", "sleep 10"]
        volumeMounts:
          - name: config-volume
            mountPath: /workspace/config

      volumes:
        - name: config-volume
          configMap:
            name: app-graceful-shutdown